apiVersion: apps/v1
kind: Deployment
metadata:
  name: testhttp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testhttp
  template:
    metadata:
      labels:
        app: testhttp
    spec:
      containers:
        - name: "cntr"
          image: "mjcr1.azurecr.io/test/http"
          imagePullPolicy: "Always"
          ports:
          - containerPort: 80
            name: cntr-port
            protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: testhttp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: testhttp